//
//  StringKey.swift
//  StickToIt
//
//  Created by 서동운 on 10/31/23.
//

import Foundation

enum StringKey {
    
    static let yes = "Yes"
    static let no = "No"
    static let done = "done"
    static let close = "close"
    static let delete = "delete"
    static let warning = "warning"
    static let cameraSettingTitle = "cameraSettingTitle"
    static let cameraSettingMessage = "cameraSettingMessage"
    static let photoPermission = "photoPermission"
    static let photoSettingMessage = "photoSettingMessage"
    static let goToPhotoSettingMessage = "goToPhotoSettingMessage"
    static let goToPhotoSetting = "goToPhotoSetting"
    static let cancel = "cancel"
    static let nickname = "nickname"
    static let nicknamePlaceholder = "nicknamePlaceholder"
    static let register = "register"
    static let planCreatedTitle = "planCreatedTitle"
    static let planCreatedMessage = "planCreatedMessage"
    static let successTodayMessage = "successTodayMessage"
    static let noti = "noti"
    static let failureTodayMessage = "failureTodayMessage"
    static let keepGoingMessage = "keepGoingMessage"
    static let congratulation = "congratulation"
    static let addPlan = "addPlan"
    static let addPlanAlert = "addPlanAlert"
    static let planList = "planList"
    static let add100Days = "add100Days"
    static let deletePlan = "deletePlan"
    static let deletePlanMessage = "deletePlanMessage"
    static let emptyViewNicknameLabel = "emptyViewNicknameLabel"
    static let userNicknameLabel = "userNicknameLabel"
    static let lastExecutionDate = "lastExecutionDate"
    static let createPlan = "createPlan"
    static let endDateTitle = "endDateTitle"
    static let endDateTitleSetting = "endDateTitleSetting"
    static let dismissMessage = "dismissMessage"
    static let planName = "planName"
    static let planNameDescription = "planNameDescription"
    static let planNamePlaceholder = "planNamePlaceholder"
    static let planStartDate = "planStartDate"
    static let planStartDateDescription = "planStartDateDescription"
    static let today = "today"
    static let tomorrow = "tomorrow"
    static let planTargetPeriodLabel = "planTargetPeriodLabel"
    static let planEndDateDescriptionLabel = "planEndDateDescriptionLabel"
    static let fontSize = "fontSize"
    static let upload = "upload"
    static let certify = "certify"
    static let certified = "certified"
    static let edit = "edit"
    static let validateNicknameLabel = "validateNicknameLabel"
    static let backup = "backup"
    static let deleteUser = "deleteUser"
    static let deleteUserMessage = "deleteUserMessage"
    static let personalSetting = "personalSetting"
    static let appInfo = "appInfo"
    static let editNickname = "editNickname"
    static let dataManagement = "dataManagement"
    static let versionInfo = "versionInfo"
    static let setting = "setting"
    static let validateLineBreak = "validateLineBreak"
    static let overTwoCharacter = "overTwoCharacter"
    static let lessThan20 = "lessThan20"
    static let userSettingDescriptionLabel = "userSettingDescriptionLabel"
    static let emptyViewTitle = "emptyViewTitle"
    static let week = "week"
    static let calendar = "calendar"
    static let home = "home"
    static let forDaysLabel = "forDaysLabel"
    static let createPlanErrorMessage = "createPlanErrorMessage"
    static let notCertified = "notCertified"
    static let todayIsNotCertifyingDay = "todayIsNotCertifyingDay"
    static let certifyingErrorMessage = "certifyingErrorMessage"
    static let saveImageErrorMessage = "saveImageErrorMessage"
    static let deleteUserErrorMessage = "deleteUserErrorMessage"
    static let certificationFailed = "certificationFailed"
    static let addImageTitle = "addImageTitle"
}


